### PR TITLE
SSE2 instruction

### PR DESCRIPTION
**Pull request by davidbullado**
- Implement pmuludq
- Automated nasm tests : Add eight 128-bit SSE registers from xmm0 to xmm8

### CODE REVIEW

**Comment by BenNottelling** [comment]
This build has failed because of an issue on google's end, so the failing test should be ignored atm

**Comment by BenNottelling** [comment]
lgtm
I don't know how I could run the other tests , but this one worked

**Comment by ElCresh** [comment]
Maybe coun be tired a "recent" version of Windows (gonna be slow but if nothing else is missing could start). Am I right?

**Comment by davidbullado** [comment]
> Maybe coun be tired a "recent" version of Windows (gonna be slow but if nothing else is missing could start). Am I right?

That would be nice, but many SSE2 & SSE1 instructions still need to be implemented :) This PR is just a first step, if its accepted I could definitively work on this :)

**Comment by davidbullado** [comment]
As it is my first PR in the project, I would like a feedback from the maintainers before implementing more :)

**Comment by davidbullado** [comment]
I just found some issues. I will close the PR and correct them.

**Comment by davidbullado** [comment]
Should be better :)

**Pull request closed without merging**
