### PR TITLE
I had < 64MB of ram and suffered

### PR DESCRIPTION
**Pull request by KernelDeimos**
I decided to put an error log here because the comment 6 frames up and 100 lines away wasn't noticed by me until after some time.

### CODE REVIEW

**Comment by copy** [comment]
I think this is a better fix: https://github.com/copy/v86/commit/2be07a1b9bade3f88cbec570a64a40dd5642d41a

**Comment by KernelDeimos** [comment]
> I think this is a better fix: [2be07a1](https://github.com/copy/v86/commit/2be07a1b9bade3f88cbec570a64a40dd5642d41a)

Yep! That said, when I encountered this error I realized I needed more than 64MiB to get anywhere.

**Comment by ProgrammerIn-wonderland** [comment]
Should this PR be closed now?

**Comment by KernelDeimos** [comment]
> Should this PR be closed now?
I think so

**Pull request closed without merging**
