### PR TITLE
readme: add SkiffOS (Buildroot) config link

### PR DESCRIPTION
**Pull request by paralin**
SkiffOS is a configuration layering system for Buildroot.

It supports re-targeting system image configs to different hardware.

The linked configuration can be combined with other layers to deploy Docker and other Linux distributions to the v86 emulator.

The configuration fragments slim down the Buildroot and Kernel systems & switch off any unnecessary features.

https://github.com/skiffos/SkiffOS/tree/master/configs/browser/v86

Demo ISO: https://drive.google.com/file/d/1UFoUEt1CQrD8B4800ii9yehff68h9IPG/view

V86 is really awesome & I was really floored to see that everything could run in it with minimal adjustments.

### CODE REVIEW

**Comment by paralin** [comment]
Docker works!

```
root@skiff-5b257f98:~# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.14
 Storage Driver: vfs
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Kernel Version: 5.18.14
 Operating System: SkiffOS 2022.05.1-16-g5b257f98
 OSType: linux
 Architecture: i686
 CPUs: 1
 Total Memory: 995.9MiB
 Name: skiff-5b257f98
 ID: 5MMI:QKUT:G4F4:KS62:P3UT:AJFR:6IPP:4YWH:Z2MU:KA7T:UOPS:TCSQ
 Docker Root Dir: /mnt/persist/skiff/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by paralin** [comment]
Dropbear SSH works too :)

image

**Comment by Darin755** [comment]
I personally think this is perfect for v86. I don't know much about it but I might use it for my personal project.

**Comment by copy** [comment]
Amazing project, thanks.

(now that docker in v86 has been shown to work, who is going to build a docker-in-the browser demo?)

**Comment by paralin** [comment]
Thanks for merging! & Thanks @Darin755 your browser-vm buildroot config is great too!

The skiff config core/alpine is a pretty decent demo, it could be added as one of the demo images, perhaps?

By the way: I enabled sse2 explicitly with -msse2 and enabling pentium 3 in buildroot. While it worked correctly, it seems sse2 is a bit slower with than without, so I disabled it for now.

**Comment by copy** [comment]
I uploaded the iso you posted here: https://copy.sh/v86/?profile=copy/skiffos

If you have an iso that includes the alpine/docker stuff feel free to post it and I'll update the profile.

**Comment by paralin** [comment]
@copy awesome 👍

The image uploaded to Google drive was updated already to include docker (afaik) but I will recompile again tomorrow with alpine specifically enabled and update it again. Will also test a few configurations to see what is fastest.

I've already replaced openssh for dropbear which starts much faster.

**Comment by paralin** [comment]
@copy https://drive.google.com/file/d/1UFoUEt1CQrD8B4800ii9yehff68h9IPG/view?usp=sharing

Updated image with:

 - Faster bootup (removed most services)
 - Dropbear instead of openssh
 - Alpine linux skiff core auto-startup
 - Persist mounted to 9p fs (not sure if maybe using HDA instead is faster?)
 - All kernel mitigations & security disabled (faster)

**Comment by copy** [comment]
@paralin Thanks, updated.

**Comment by paralin** [comment]
@copy @Darin755 Here's a link to the saved state of the VM (with the latest copy/skiffos image) after it boots up & downloads + starts the Alpine linux container.

https://drive.google.com/file/d/1SZsgpEb1qN3vb89JE516hsrlMpLmH9qo/view?usp=sharing

Downloading & extracting the Alpine image takes a little while (but is completed in the above snapshot).

**Comment by copy** [comment]
@paralin As a suggestion to shrink the state size, you could add `CONFIG_PAGE_POISONING=y` and `page_poison=on` on the kernel command line. It seems that on modern kernels, `init_on_free=on` might be sufficient, but I haven't tried it yet.

**Comment by paralin** [comment]
@copy OK - done: https://github.com/skiffos/SkiffOS/commit/564fc6a7ce24fd05b58d3f852ecba2545916d09d

I will rebuild & make a new image + state snapshot soon.

**Comment by paralin** [comment]
@copy Updated to latest SkiffOS with kernel 5.19.12: https://drive.google.com/file/d/1UFoUEt1CQrD8B4800ii9yehff68h9IPG/view

And the updated state file with Alpine Edge running: https://drive.google.com/file/d/1SZsgpEb1qN3vb89JE516hsrlMpLmH9qo/view

image

Memory usage is ~46M and persist storage ~32M right now w/ Alpine, switching to the recently added `apps/podman` from Docker would reduce it even more - but some work remains to make skiff-core support it.

@copy This is using `tsc=reliable mitigations=off random.trust_cpu=on page_poison=on init_on_free=on` but the state file is  ~628Mb, any ideas why it's so large?

image

Root FS size can be reduced by making a mono-binary which merges all docker-related binaries together.

**Comment by copy** [comment]
I suspect removing `page_poison=on` would fix the size. In older kernels it was the only way to get zeroed pages (together with `CONFIG_PAGE_POISONING_ZERO=y`). Now `init_on_free=on` does that.

**Comment by paralin** [comment]
@copy With these settings, 

`tsc=reliable mitigations=off random.trust_cpu=on init_on_free=on`

kernel config: https://gist.github.com/paralin/231aa989f8457f9c1b857b6385693ca9

I'll try enabling `CONFIG_INIT_ON_FREE_DEFAULT_ON`. According to the description of that option, the kernel cmdline should actually be `init_on_free=1` (as opposed to `on`) but I don't know, maybe `on` also works.

**Comment by paralin** [comment]
@copy The images have been updated with these optimizations:

 - [iso image](https://drive.google.com/file/d/1UFoUEt1CQrD8B4800ii9yehff68h9IPG/view)
 - [state file](https://drive.google.com/file/d/1SZsgpEb1qN3vb89JE516hsrlMpLmH9qo/view)
 - [kernel config](https://github.com/skiffos/SkiffOS/blob/master/configs/browser/v86/kernel/04-optimize)

It seems to be much faster now! Although the state is still 486MB.

**Comment by paralin** [comment]
Hi @copy - I was wondering if you had a chance to update the image at https://copy.sh/v86/?profile=copy/skiffos with the above improvements? I'm using it as a demo link in the project readme currently.

would it be of interest to add skiffos to the list of demos in v86 as well?

Thanks again!

**Comment by copy** [comment]
@paralin Updated, thanks!

I noticed that docker downloads some large files during startup (not sure if it's pulling images or something else). That could cause the state size to blow up, since any data written to disk or tmpfs needs to be saved in the state file. It's also sub-optimal, since all the traffic goes through the public websocket relay.

> would it be of interest to add skiffos to the list of demos in v86 as well?

I'll think about it. At the moment the front page is pretty messy, and already contains three linux distributions. I'm considering a column layout (à la https://winworldpc.com/library/operating-systems) or a "more profiles" button.

**Comment by paralin** [comment]
@copy ah, that'll be because it's downloading and running alpine linux. I'll have a look at using the lazy-fetching stargz format for it instead, which would download files on first access

**Pull request merged**
