### PR TITLE
Fix release artifact upload.

### PR DESCRIPTION
**Pull request by basicer**
Fixes publishing build artifacts into the latest release and also builds and includes the fallback wasm build.

### CODE REVIEW

**Comment by basicer** [comment]
Also something is going on with the nasm tests on CI where they pass if they use the cache but fail for clean builds.

**Comment by copy** [comment]
Thanks! I'm a bit busy right now, will look at this again in two weeks.

**Comment by copy** [comment]
> Also something is going on with the nasm tests on CI where they pass if they use the cache but fail for clean builds.

If you rebase on master this should be fixed, and then good to merge.

**Comment by copy** [comment]
Thanks!

**Pull request merged**
